apiVersion: v1
data: {}
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
      smtp_from: 'alert@rp-pet.cn'
      smtp_smarthost: 'smtp.exmail.qq.com:465'
      smtp_auth_username: 'alert@rt.cn'
      smtp_auth_password: 'bk7hNBdFpBgH'
      smtp_require_tls: false
      smtp_hello: '.cn'
    route:
      group_by: ['alertname']
      group_wait: 15s
      group_interval: 2h
      repeat_interval: 24h
      receiver: 'email'
    receivers:
    - name: 'email'
      email_configs:
      - to: 'dut.cn'
        send_resolved: true
type: Opaque
