---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: k8s-ingress-nginx
  labels:
    k8s-app: k8s-ingress-nginx
spec:
  type: ClusterIP
  ports:
    - name: https-metrics
      port: 10254
      targetPort: 10254
      protocol: TCP
  selector:
    app: ingress-nginx
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: k8s-ingress-nginx
  name: k8s-ingress-nginx
  namespace: monitoring
spec:
  endpoints:
  - port: https-metrics
    interval: 30s
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: k8s-ingress-nginx
    #在etcd的主机上执行：kubectl -n monitoring create secret generic etcd-secret --from-file=etcd-ca=/path to/certs/ca/ca.pem --from-file=etcd-cert=/path/certs/etcd/etcd.pem --from-file=etcd-key=/path/certs/etcd/etcd-key.pem    (aliyun path=/var/lib)
